version: '3.8'

services:
  app:
    build: .
    command: node dist/src/main.js #untuk production
    stdin_open: true  
    tty: true    
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@db:5432/Dashboard?schema=public
      REDIS_URL: redis://redis:6379
    # volumes:
      # - ./:/usr/src/app
      # - /usr/src/app/node_modules
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Dashboard
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata: